trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: terraform-dev
  - name: IMAGE_TAG
    value: $(Build.BuildNumber)

stages:
- stage: BuildAndPush
  displayName: Build & Push Image
  jobs:
  - job: Build
    displayName: Docker Build & Push
    steps:
    - checkout: self

    - bash: |
        set -e
        az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID" >/dev/null
        az account set --subscription "$ARM_SUBSCRIPTION_ID"

        ACR_LOGIN_SERVER=$(az acr show -n "$(ACR_NAME)" --query loginServer -o tsv)
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"
        echo "##vso[task.setvariable variable=ACR_LOGIN_SERVER]$ACR_LOGIN_SERVER"
      displayName: "Auth: Azure login + resolve ACR"
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

    - bash: |
        set -e
        echo "Installing tfsec..."
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

        echo "Running tfsec..."
        tfsec terraform/environments/dev || true
      displayName: "Security: tfsec (Terraform)"

    - bash: |
        set -e
        docker build -t "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)" app/PlatformApi
        docker tag "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)" "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest"
      displayName: "Build: Docker build"

    - bash: |
        set -e
        sudo apt-get update -y
        sudo apt-get install -y wget gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/v2/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/v2/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

        trivy image --severity HIGH,CRITICAL --exit-code 1 "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)"
      displayName: "Security: Trivy image scan"

    - bash: |
        set -e
        az acr login -n "$(ACR_NAME)"
        docker push "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)"
        docker push "$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest"
      displayName: "Push: Docker push to ACR"


- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployToDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - bash: |
              set -e

              echo "Logging into Azure with service principal..."
              az login --service-principal \
                -u "$ARM_CLIENT_ID" \
                -p "$ARM_CLIENT_SECRET" \
                --tenant "$ARM_TENANT_ID" >/dev/null

              az account set --subscription "$ARM_SUBSCRIPTION_ID"

              ACR_LOGIN_SERVER=$(az acr show -n "$(ACR_NAME)" --query loginServer -o tsv)
              echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"              

              echo "Getting AKS credentials..."
              az aks get-credentials -g "$(AKS_RG)" -n "$(AKS_NAME)" --overwrite-existing

              echo "Deploying Helm release..."
              helm upgrade --install "$(HELM_RELEASE)" helm/platform-api \
                --namespace "$(HELM_NAMESPACE)" \
                --create-namespace \
                --set image.repository="$ACR_LOGIN_SERVER/$(IMAGE_NAME)" \
                --set image.tag="$(IMAGE_TAG)" \
                --set workloadIdentity.clientId="$(WORKLOAD_IDENTITY_CLIENT_ID)" \
                --set workloadIdentity.tenantId="$(ARM_TENANT_ID)" \
                --set keyVault.name="$(KEY_VAULT_NAME)" \
                --set containerPort=8080 \
                --set service.port=80

              echo "Waiting for rollout..."
              kubectl rollout status deploy/"$(HELM_RELEASE)" -n "$(HELM_NAMESPACE)" --timeout=180s

              echo "Pods:"
              kubectl get pods -n "$(HELM_NAMESPACE)"
            displayName: Helm Deploy
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
