trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: terraform-dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: TerraformPlan
  displayName: Terraform Plan
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - script: |
        terraform init \
          -backend-config="resource_group_name=$(TF_STATE_RG)" \
          -backend-config="storage_account_name=$(TF_STATE_STORAGE)" \
          -backend-config="container_name=$(TF_STATE_CONTAINER)" \
          -backend-config="key=$(TF_STATE_KEY)"
        terraform validate
        terraform plan -out=tfplan
      workingDirectory: terraform/environments/dev
      displayName: Terraform Init/Plan
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

    - publish: terraform/environments/dev/tfplan
      artifact: tfplan
      displayName: Publish tfplan

- stage: TerraformApply
  displayName: Terraform Apply
  dependsOn: TerraformPlan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Apply
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'

          - download: current
            artifact: tfplan

          - script: |
              terraform init \
                -backend-config="resource_group_name=$(TF_STATE_RG)" \
                -backend-config="storage_account_name=$(TF_STATE_STORAGE)" \
                -backend-config="container_name=$(TF_STATE_CONTAINER)" \
                -backend-config="key=$(TF_STATE_KEY)"
              terraform apply -auto-approve tfplan
            workingDirectory: terraform/environments/dev
            displayName: Terraform Apply
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
