trigger: none
pr: none

variables:
  - group: terraform-dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: TerraformPlanDestroy
  displayName: Terraform Plan (Destroy)
  jobs:
  - job: PlanDestroy
    displayName: Plan Destroy
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - script: |
        terraform init \
          -backend-config="resource_group_name=$(TF_STATE_RG)" \
          -backend-config="storage_account_name=$(TF_STATE_STORAGE)" \
          -backend-config="container_name=$(TF_STATE_CONTAINER)" \
          -backend-config="key=$(TF_STATE_KEY)"
        terraform validate
        terraform plan -destroy -out=tfdestroyplan
      workingDirectory: terraform/environments/dev
      displayName: Terraform Init/Plan (Destroy)
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        
    - script: |
        terraform init \
          -reconfigure \
          -backend-config="resource_group_name=$(TF_STATE_RG)" \
          -backend-config="storage_account_name=$(TF_STATE_STORAGE)" \
          -backend-config="container_name=$(TF_STATE_CONTAINER)" \
          -backend-config="key=$(TF_STATE_KEY)"

        echo "Forcing unlock (safe only if no other TF run is active)..."
        terraform force-unlock -force 695ce98c-ee4e-aa8c-11e3-dc28e185b201
      workingDirectory: terraform/environments/dev
      displayName: Terraform Init + Force Unlock
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)


    - publish: terraform/environments/dev/tfdestroyplan
      artifact: tfdestroyplan
      displayName: Publish tfdestroyplan

- stage: TerraformApplyDestroy
  displayName: Terraform Destroy (Apply)
  dependsOn: TerraformPlanDestroy
  # Keep this gate if you only want destroy allowed from main
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Destroy
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'

          - download: current
            artifact: tfdestroyplan

          - bash: |
              echo "Pipeline.Workspace = $(Pipeline.Workspace)"
              echo "Listing workspace:"
              ls -la "$(Pipeline.Workspace)"
              echo "Listing tfdestroyplan artifact folder:"
              ls -la "$(Pipeline.Workspace)/tfdestroyplan"
            displayName: Debug downloaded tfdestroyplan

          - script: |
              terraform init \
                -reconfigure \
                -backend-config="resource_group_name=$(TF_STATE_RG)" \
                -backend-config="storage_account_name=$(TF_STATE_STORAGE)" \
                -backend-config="container_name=$(TF_STATE_CONTAINER)" \
                -backend-config="key=$(TF_STATE_KEY)"

              terraform apply -auto-approve "$(Pipeline.Workspace)/tfdestroyplan/tfdestroyplan"
            workingDirectory: terraform/environments/dev
            displayName: Terraform Destroy (Apply)
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
